export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCES'
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR'

export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'

export const PRODUCT_EDIT = 'PRODUCT_EDITION'
export const START_PRODUCT_EDITION = 'START_PRODUCT_EDITION'
export const PRODUCT_EDITION_SUCCESS = 'PRODUCT_EDITION_SUCCESS'
export const PRODUCT_EDITION_ERROR = 'PRODUCT_EDITION_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
